/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdvertisingRouteImport } from './routes/advertising'
import { Route as AffiliateGuideRouteImport } from './routes/affiliate-guide'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as BecomeAMemberRouteImport } from './routes/become-a-member'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GlobalNetworkRouteImport } from './routes/global-network'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as NewsRouteImport } from './routes/news'
import { Route as OurMembersRouteImport } from './routes/our-members'
import { Route as WbcTeamRouteImport } from './routes/wbc-team'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as AffiliatesIndexRouteImport } from './routes/affiliates.index'
import { Route as AffiliatesSlugRouteImport } from './routes/affiliates.$slug'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as GlobalNetworkIndexRouteImport } from './routes/global-network.index'
import { Route as GlobalNetworkHeadquartersRouteImport } from './routes/global-network.headquarters'
import { Route as GlobalNetworkInstitutionalMembersRouteImport } from './routes/global-network.institutional-members'
import { Route as GlobalNetworkStrategicPartnersRouteImport } from './routes/global-network.strategic-partners'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as MembershipIndexRouteImport } from './routes/membership.index'
import { Route as MembershipBenefitsRouteImport } from './routes/membership.benefits'
import { Route as WbcTeamIndexRouteImport } from './routes/wbc-team.index'
import { Route as WbcTeamSlugRouteImport } from './routes/wbc-team.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvertisingRoute = AdvertisingRouteImport.update({
  id: '/advertising',
  path: '/advertising',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateGuideRoute = AffiliateGuideRouteImport.update({
  id: '/affiliate-guide',
  path: '/affiliate-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAMemberRoute = BecomeAMemberRouteImport.update({
  id: '/become-a-member',
  path: '/become-a-member',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalNetworkRoute = GlobalNetworkRouteImport.update({
  id: '/global-network',
  path: '/global-network',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const OurMembersRoute = OurMembersRouteImport.update({
  id: '/our-members',
  path: '/our-members',
  getParentRoute: () => rootRouteImport,
} as any)
const WbcTeamRoute = WbcTeamRouteImport.update({
  id: '/wbc-team',
  path: '/wbc-team',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesIndexRoute = AffiliatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AffiliatesRoute,
} as any)
const AffiliatesSlugRoute = AffiliatesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AffiliatesRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const GlobalNetworkIndexRoute = GlobalNetworkIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GlobalNetworkRoute,
} as any)
const GlobalNetworkHeadquartersRoute =
  GlobalNetworkHeadquartersRouteImport.update({
    id: '/headquarters',
    path: '/headquarters',
    getParentRoute: () => GlobalNetworkRoute,
  } as any)
const GlobalNetworkInstitutionalMembersRoute =
  GlobalNetworkInstitutionalMembersRouteImport.update({
    id: '/institutional-members',
    path: '/institutional-members',
    getParentRoute: () => GlobalNetworkRoute,
  } as any)
const GlobalNetworkStrategicPartnersRoute =
  GlobalNetworkStrategicPartnersRouteImport.update({
    id: '/strategic-partners',
    path: '/strategic-partners',
    getParentRoute: () => GlobalNetworkRoute,
  } as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JobsRoute,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => JobsRoute,
} as any)
const MembershipIndexRoute = MembershipIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembershipRoute,
} as any)
const MembershipBenefitsRoute = MembershipBenefitsRouteImport.update({
  id: '/benefits',
  path: '/benefits',
  getParentRoute: () => MembershipRoute,
} as any)
const WbcTeamIndexRoute = WbcTeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WbcTeamRoute,
} as any)
const WbcTeamSlugRoute = WbcTeamSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WbcTeamRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/affiliate-guide': typeof AffiliateGuideRoute
  '/affiliates': typeof AffiliatesRouteWithChildren
  '/become-a-member': typeof BecomeAMemberRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/jobs': typeof JobsRouteWithChildren
  '/membership': typeof MembershipRouteWithChildren
  '/news': typeof NewsRoute
  '/our-members': typeof OurMembersRoute
  '/wbc-team': typeof WbcTeamRouteWithChildren
  '/what-we-do': typeof WhatWeDoRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/affiliates/$slug': typeof AffiliatesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/global-network/headquarters': typeof GlobalNetworkHeadquartersRoute
  '/global-network/institutional-members': typeof GlobalNetworkInstitutionalMembersRoute
  '/global-network/strategic-partners': typeof GlobalNetworkStrategicPartnersRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/membership/benefits': typeof MembershipBenefitsRoute
  '/wbc-team/$slug': typeof WbcTeamSlugRoute
  '/affiliates/': typeof AffiliatesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/global-network/': typeof GlobalNetworkIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/wbc-team/': typeof WbcTeamIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/affiliate-guide': typeof AffiliateGuideRoute
  '/become-a-member': typeof BecomeAMemberRoute
  '/contact': typeof ContactRoute
  '/governance': typeof GovernanceRoute
  '/news': typeof NewsRoute
  '/our-members': typeof OurMembersRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/affiliates/$slug': typeof AffiliatesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/global-network/headquarters': typeof GlobalNetworkHeadquartersRoute
  '/global-network/institutional-members': typeof GlobalNetworkInstitutionalMembersRoute
  '/global-network/strategic-partners': typeof GlobalNetworkStrategicPartnersRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/membership/benefits': typeof MembershipBenefitsRoute
  '/wbc-team/$slug': typeof WbcTeamSlugRoute
  '/affiliates': typeof AffiliatesIndexRoute
  '/events': typeof EventsIndexRoute
  '/global-network': typeof GlobalNetworkIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/membership': typeof MembershipIndexRoute
  '/wbc-team': typeof WbcTeamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/advertising': typeof AdvertisingRoute
  '/affiliate-guide': typeof AffiliateGuideRoute
  '/affiliates': typeof AffiliatesRouteWithChildren
  '/become-a-member': typeof BecomeAMemberRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/global-network': typeof GlobalNetworkRouteWithChildren
  '/governance': typeof GovernanceRoute
  '/jobs': typeof JobsRouteWithChildren
  '/membership': typeof MembershipRouteWithChildren
  '/news': typeof NewsRoute
  '/our-members': typeof OurMembersRoute
  '/wbc-team': typeof WbcTeamRouteWithChildren
  '/what-we-do': typeof WhatWeDoRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/affiliates/$slug': typeof AffiliatesSlugRoute
  '/events/$slug': typeof EventsSlugRoute
  '/global-network/headquarters': typeof GlobalNetworkHeadquartersRoute
  '/global-network/institutional-members': typeof GlobalNetworkInstitutionalMembersRoute
  '/global-network/strategic-partners': typeof GlobalNetworkStrategicPartnersRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/membership/benefits': typeof MembershipBenefitsRoute
  '/wbc-team/$slug': typeof WbcTeamSlugRoute
  '/affiliates/': typeof AffiliatesIndexRoute
  '/events/': typeof EventsIndexRoute
  '/global-network/': typeof GlobalNetworkIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/membership/': typeof MembershipIndexRoute
  '/wbc-team/': typeof WbcTeamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/advertising'
    | '/affiliate-guide'
    | '/affiliates'
    | '/become-a-member'
    | '/contact'
    | '/events'
    | '/global-network'
    | '/governance'
    | '/jobs'
    | '/membership'
    | '/news'
    | '/our-members'
    | '/wbc-team'
    | '/what-we-do'
    | '/who-we-are'
    | '/affiliates/$slug'
    | '/events/$slug'
    | '/global-network/headquarters'
    | '/global-network/institutional-members'
    | '/global-network/strategic-partners'
    | '/jobs/$slug'
    | '/membership/benefits'
    | '/wbc-team/$slug'
    | '/affiliates/'
    | '/events/'
    | '/global-network/'
    | '/jobs/'
    | '/membership/'
    | '/wbc-team/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/advertising'
    | '/affiliate-guide'
    | '/become-a-member'
    | '/contact'
    | '/governance'
    | '/news'
    | '/our-members'
    | '/what-we-do'
    | '/who-we-are'
    | '/affiliates/$slug'
    | '/events/$slug'
    | '/global-network/headquarters'
    | '/global-network/institutional-members'
    | '/global-network/strategic-partners'
    | '/jobs/$slug'
    | '/membership/benefits'
    | '/wbc-team/$slug'
    | '/affiliates'
    | '/events'
    | '/global-network'
    | '/jobs'
    | '/membership'
    | '/wbc-team'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/advertising'
    | '/affiliate-guide'
    | '/affiliates'
    | '/become-a-member'
    | '/contact'
    | '/events'
    | '/global-network'
    | '/governance'
    | '/jobs'
    | '/membership'
    | '/news'
    | '/our-members'
    | '/wbc-team'
    | '/what-we-do'
    | '/who-we-are'
    | '/affiliates/$slug'
    | '/events/$slug'
    | '/global-network/headquarters'
    | '/global-network/institutional-members'
    | '/global-network/strategic-partners'
    | '/jobs/$slug'
    | '/membership/benefits'
    | '/wbc-team/$slug'
    | '/affiliates/'
    | '/events/'
    | '/global-network/'
    | '/jobs/'
    | '/membership/'
    | '/wbc-team/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdvertisingRoute: typeof AdvertisingRoute
  AffiliateGuideRoute: typeof AffiliateGuideRoute
  AffiliatesRoute: typeof AffiliatesRouteWithChildren
  BecomeAMemberRoute: typeof BecomeAMemberRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  GlobalNetworkRoute: typeof GlobalNetworkRouteWithChildren
  GovernanceRoute: typeof GovernanceRoute
  JobsRoute: typeof JobsRouteWithChildren
  MembershipRoute: typeof MembershipRouteWithChildren
  NewsRoute: typeof NewsRoute
  OurMembersRoute: typeof OurMembersRoute
  WbcTeamRoute: typeof WbcTeamRouteWithChildren
  WhatWeDoRoute: typeof WhatWeDoRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advertising': {
      id: '/advertising'
      path: '/advertising'
      fullPath: '/advertising'
      preLoaderRoute: typeof AdvertisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-guide': {
      id: '/affiliate-guide'
      path: '/affiliate-guide'
      fullPath: '/affiliate-guide'
      preLoaderRoute: typeof AffiliateGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-member': {
      id: '/become-a-member'
      path: '/become-a-member'
      fullPath: '/become-a-member'
      preLoaderRoute: typeof BecomeAMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-network': {
      id: '/global-network'
      path: '/global-network'
      fullPath: '/global-network'
      preLoaderRoute: typeof GlobalNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-members': {
      id: '/our-members'
      path: '/our-members'
      fullPath: '/our-members'
      preLoaderRoute: typeof OurMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wbc-team': {
      id: '/wbc-team'
      path: '/wbc-team'
      fullPath: '/wbc-team'
      preLoaderRoute: typeof WbcTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates/': {
      id: '/affiliates/'
      path: '/'
      fullPath: '/affiliates/'
      preLoaderRoute: typeof AffiliatesIndexRouteImport
      parentRoute: typeof AffiliatesRoute
    }
    '/affiliates/$slug': {
      id: '/affiliates/$slug'
      path: '/$slug'
      fullPath: '/affiliates/$slug'
      preLoaderRoute: typeof AffiliatesSlugRouteImport
      parentRoute: typeof AffiliatesRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/global-network/': {
      id: '/global-network/'
      path: '/'
      fullPath: '/global-network/'
      preLoaderRoute: typeof GlobalNetworkIndexRouteImport
      parentRoute: typeof GlobalNetworkRoute
    }
    '/global-network/headquarters': {
      id: '/global-network/headquarters'
      path: '/headquarters'
      fullPath: '/global-network/headquarters'
      preLoaderRoute: typeof GlobalNetworkHeadquartersRouteImport
      parentRoute: typeof GlobalNetworkRoute
    }
    '/global-network/institutional-members': {
      id: '/global-network/institutional-members'
      path: '/institutional-members'
      fullPath: '/global-network/institutional-members'
      preLoaderRoute: typeof GlobalNetworkInstitutionalMembersRouteImport
      parentRoute: typeof GlobalNetworkRoute
    }
    '/global-network/strategic-partners': {
      id: '/global-network/strategic-partners'
      path: '/strategic-partners'
      fullPath: '/global-network/strategic-partners'
      preLoaderRoute: typeof GlobalNetworkStrategicPartnersRouteImport
      parentRoute: typeof GlobalNetworkRoute
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof JobsRoute
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof JobsRoute
    }
    '/membership/': {
      id: '/membership/'
      path: '/'
      fullPath: '/membership/'
      preLoaderRoute: typeof MembershipIndexRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/membership/benefits': {
      id: '/membership/benefits'
      path: '/benefits'
      fullPath: '/membership/benefits'
      preLoaderRoute: typeof MembershipBenefitsRouteImport
      parentRoute: typeof MembershipRoute
    }
    '/wbc-team/': {
      id: '/wbc-team/'
      path: '/'
      fullPath: '/wbc-team/'
      preLoaderRoute: typeof WbcTeamIndexRouteImport
      parentRoute: typeof WbcTeamRoute
    }
    '/wbc-team/$slug': {
      id: '/wbc-team/$slug'
      path: '/$slug'
      fullPath: '/wbc-team/$slug'
      preLoaderRoute: typeof WbcTeamSlugRouteImport
      parentRoute: typeof WbcTeamRoute
    }
  }
}

interface AffiliatesRouteChildren {
  AffiliatesSlugRoute: typeof AffiliatesSlugRoute
  AffiliatesIndexRoute: typeof AffiliatesIndexRoute
}

const AffiliatesRouteChildren: AffiliatesRouteChildren = {
  AffiliatesSlugRoute: AffiliatesSlugRoute,
  AffiliatesIndexRoute: AffiliatesIndexRoute,
}

const AffiliatesRouteWithChildren = AffiliatesRoute._addFileChildren(
  AffiliatesRouteChildren,
)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface GlobalNetworkRouteChildren {
  GlobalNetworkHeadquartersRoute: typeof GlobalNetworkHeadquartersRoute
  GlobalNetworkInstitutionalMembersRoute: typeof GlobalNetworkInstitutionalMembersRoute
  GlobalNetworkStrategicPartnersRoute: typeof GlobalNetworkStrategicPartnersRoute
  GlobalNetworkIndexRoute: typeof GlobalNetworkIndexRoute
}

const GlobalNetworkRouteChildren: GlobalNetworkRouteChildren = {
  GlobalNetworkHeadquartersRoute: GlobalNetworkHeadquartersRoute,
  GlobalNetworkInstitutionalMembersRoute:
    GlobalNetworkInstitutionalMembersRoute,
  GlobalNetworkStrategicPartnersRoute: GlobalNetworkStrategicPartnersRoute,
  GlobalNetworkIndexRoute: GlobalNetworkIndexRoute,
}

const GlobalNetworkRouteWithChildren = GlobalNetworkRoute._addFileChildren(
  GlobalNetworkRouteChildren,
)

interface JobsRouteChildren {
  JobsSlugRoute: typeof JobsSlugRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsSlugRoute: JobsSlugRoute,
  JobsIndexRoute: JobsIndexRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface MembershipRouteChildren {
  MembershipBenefitsRoute: typeof MembershipBenefitsRoute
  MembershipIndexRoute: typeof MembershipIndexRoute
}

const MembershipRouteChildren: MembershipRouteChildren = {
  MembershipBenefitsRoute: MembershipBenefitsRoute,
  MembershipIndexRoute: MembershipIndexRoute,
}

const MembershipRouteWithChildren = MembershipRoute._addFileChildren(
  MembershipRouteChildren,
)

interface WbcTeamRouteChildren {
  WbcTeamSlugRoute: typeof WbcTeamSlugRoute
  WbcTeamIndexRoute: typeof WbcTeamIndexRoute
}

const WbcTeamRouteChildren: WbcTeamRouteChildren = {
  WbcTeamSlugRoute: WbcTeamSlugRoute,
  WbcTeamIndexRoute: WbcTeamIndexRoute,
}

const WbcTeamRouteWithChildren =
  WbcTeamRoute._addFileChildren(WbcTeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdvertisingRoute: AdvertisingRoute,
  AffiliateGuideRoute: AffiliateGuideRoute,
  AffiliatesRoute: AffiliatesRouteWithChildren,
  BecomeAMemberRoute: BecomeAMemberRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  GlobalNetworkRoute: GlobalNetworkRouteWithChildren,
  GovernanceRoute: GovernanceRoute,
  JobsRoute: JobsRouteWithChildren,
  MembershipRoute: MembershipRouteWithChildren,
  NewsRoute: NewsRoute,
  OurMembersRoute: OurMembersRoute,
  WbcTeamRoute: WbcTeamRouteWithChildren,
  WhatWeDoRoute: WhatWeDoRoute,
  WhoWeAreRoute: WhoWeAreRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
